# Generated by Django 5.0 on 2024-01-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('1A', 'AC First Class'), ('2A', 'AC Second Class'), ('3A', 'AC Third Class'), ('SL', 'Sleeper Class'), ('GN', 'General Class')]),
        ),
        migrations.AlterField(
            model_name='coach',
            name='code',
            field=models.CharField(),
        ),
    ]
