# Generated by Django 5.0 on 2024-01-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_coach_coach_type_alter_coach_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('1A', 'AC First Class'), ('2A', 'AC Second Class'), ('3A', 'AC Third Class'), ('SL', 'Sleeper Class'), ('GN', 'General Class')], max_length=2),
        ),
        migrations.AlterField(
            model_name='coach',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(max_length=6),
        ),
    ]
