# Generated by Django 5.0 on 2024-01-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_coach_coach_type_alter_coach_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatreservation',
            name='bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_reservation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reservation.seatreservation'),
            preserve_default=False,
        ),
    ]
