# Generated by Django 5.0 on 2024-01-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_seatreservation_bookings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bookings',
        ),
    ]
