# Generated by Django 5.0 on 2024-01-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_account_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatreservation',
            name='seat_number',
            field=models.CharField(max_length=6),
        ),
    ]
