# Generated by Django 5.0 on 2024-01-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_account_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
